/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbiter.v:1" *)
module arbiter(clock, reset, req_0, req_1, gnt_0, gnt_1);
  (* src = "arbiter.v:16" *)
  wire _00_;
  (* src = "arbiter.v:16" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "arbiter.v:10" *)
  input clock;
  (* src = "arbiter.v:11" *)
  output gnt_0;
  (* src = "arbiter.v:11" *)
  output gnt_1;
  (* src = "arbiter.v:10" *)
  input req_0;
  (* src = "arbiter.v:10" *)
  input req_1;
  (* src = "arbiter.v:10" *)
  input reset;
  NOT _08_ (
    .A(gnt_0),
    .Y(_06_)
  );
  NOR _09_ (
    .A(req_1),
    .B(gnt_1),
    .Y(_07_)
  );
  NOR _10_ (
    .A(req_0),
    .B(_07_),
    .Y(_02_)
  );
  NOT _11_ (
    .A(_02_),
    .Y(_03_)
  );
  NOR _12_ (
    .A(reset),
    .B(_03_),
    .Y(_01_)
  );
  NOR _13_ (
    .A(_06_),
    .B(req_1),
    .Y(_04_)
  );
  NOR _14_ (
    .A(req_0),
    .B(_04_),
    .Y(_05_)
  );
  NOR _15_ (
    .A(reset),
    .B(_05_),
    .Y(_00_)
  );
  (* src = "arbiter.v:16" *)
  DFF _16_ (
    .C(clock),
    .D(_00_),
    .Q(gnt_0)
  );
  (* src = "arbiter.v:16" *)
  DFF _17_ (
    .C(clock),
    .D(_01_),
    .Q(gnt_1)
  );
endmodule
